server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://118.31.17.219:3306/here_web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Here123456.
  redis:
    host: 118.31.17.219 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: Here123456. # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info
    com.here: debug

wechart:
  appid: wx209e3f1fc444d6e1
  secret: 97e2db0e59e0cbf08e606490ad228ac4
  login_url: https://api.weixin.qq.com/sns/jscode2session
  acctoken_url:  https://api.weixin.qq.com/cgi-bin/token
  redirect_uri:
douyin:
  client_key: 123
  client_secret: 123
  token_url: https://developer.toutiao.com/api/apps/v2/token
  login_url: https://developer.toutiao.com/api/apps/v2/jscode2session

