spring:
  datasource:
    url: jdbc:mysql://121.43.178.221:3306/here_web?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Here123456.
  redis:
    host: 121.43.178.221 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info
    com.here: debug

wechart:
  appid: wx209e3f1fc444d6e1
  secret: 97e2db0e59e0cbf08e606490ad228ac4
  login_url: https://api.weixin.qq.com/sns/jscode2session
  acctoken_url:  https://api.weixin.qq.com/cgi-bin/token
  redirect_uri:
  jsapi: https://api.mch.weixin.qq.com/v3/pay/transactions/jsapi # JSAPI下单

douyin:
  client_key: 123
  client_secret: 123
  token_url: https://developer.toutiao.com/api/apps/v2/token
  login_url: https://developer.toutiao.com/api/apps/v2/jscode2session

server:
  port: 9999
  ssl:
    # key-alias: tomcat
    # 填写pfx-password.txt文件内的密码。
    key-store-password: c4u9j47q
    key-store-type: PKCS12
    #您需要使用实际的证书名称替换domain_name.pfx。
    key-store: classpath:8872904_wxapi.qingdu-inc.top.pfx

oss:
  access-key-id:
  access-key-secret:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  bucket-name: qd-resource
  folder-name: goods/image